### ISSUE TITLE
How did you get into programming?

### ISSUE THREAD

**Issue by arthurvr** [silvenon/ama#3]

**Comment by silvenon** [comment]
Simultaneously by reading W3Schools (ugh) and by… \*drumroll\*… making maps in Warcraft.

Learning web design was an on-and-off relationships, I tried a few times and gave up, but the last time I stuck around :)

Warcraft has a scripting language, [JASS](https://en.wikipedia.org/wiki/JASS), which is much more performant when you write in it directly, rather than generating it under-the-hood with the GUI. Also, some crazy dude made a JASS preprocessor—vJASS—which made it much easier to code in (like Sass is easier than CSS). So with the evolution of this "language" I learned some basic programming concepts.
