### ISSUE TITLE
What's your favorite movie or TV show?

### ISSUE THREAD

**Issue by arthurvr** [silvenon/ama#7]

**Comment by silvenon** [comment]
I can't decide between these three TV shows:

* [Sherlock](http://www.imdb.com/title/tt1475582/?ref_=nv_sr_1)
* [Hannibal](http://www.imdb.com/title/tt2243973/?ref_=nv_sr_1)
* [Orange is the New Black](http://www.imdb.com/title/tt2372162/?ref_=nv_sr_1)

Sherlock has so many brilliant scenes and characters. James Moriarty is a fascinating character, you don't simply hate him like you hate Joffrey in Game of Thrones, with Moriarty your tuned into his every action, even every facial expression. The actor is amazing.

Hannibal is very strange, scary and morbid, I love it. It's so different than many popular horror shows, there's not a single cliché moment. The characters are amazing, it has so many brilliant scenes and dialogues really make you think constantly.

Orange is the New Black is an excellent and very important show. It teaches you so many valuable things about love, LGBT, feminism, racism, religion, spiritualism… It touches on so many important subjects in a very mature way. There are so many love movies which don't know the first thing about how relationships work (for example [The Story of Us](http://www.imdb.com/title/tt0160916/?ref_=nv_sr_2)) and often tell us to negate incompatibility in our relationships and force them to work, because love is sacred or something. Orange is the New Black has a very realistic and loving view on relationships, the one which is actually useful. It has everything, from humor to some really scary shit.

The movies are a lot harder because there are so many of them, but recently I've seen [Ex Machina](http://www.imdb.com/title/tt0470752/?ref_=nv_sr_1), which I really enjoyed. It has almost no music, so there's nothing to manipulate your emotions, a lot of it is just dialogue and it's very interesting and intense.
